<?php

define("ECOSYSTEM_ITEMS", [
    'breeze' => [
        'id' => 'breeze',
        'name' => 'Breeze',
        'image-alt' => 'Laravel Breeze',
        'description' => 'Lightweight starter kit scaffolding for new applications with Blade or Inertia.',
        'href' => '/docs/' . DEFAULT_VERSION . '/starter-kits#laravel-breeze',
    ],
    'cashier' => [
        'id' => 'cashier',
        'name' => 'Cashier',
        'image-alt' => 'Laravel Cashier',
        'description' => 'Take the pain out of managing subscriptions on Stripe or Paddle.',
        'href' => '/docs/' . DEFAULT_VERSION . '/billing',
    ],
    'dusk' => [
        'id' => 'dusk',
        'name' => 'Dusk',
        'image-alt' => 'Laravel Dusk',
        'description' => 'Automated browser testing to ship your application with confidence.',
        'href' => '/docs/' . DEFAULT_VERSION . '/dusk',
    ],
    'echo' => [
        'id' => 'echo',
        'name' => 'Echo',
        'image-alt' => 'Laravel Echo',
        'description' => 'Listen for WebSocket events broadcast by your Laravel application.',
        'href' => '/docs/' . DEFAULT_VERSION . '/broadcasting',
    ],
    'envoyer' => [
        'id' => 'envoyer',
        'name' => 'Envoyer',
        'image-alt' => 'Envoyer',
        'description' => 'Deploy your Laravel applications to customers with zero downtime.',
        'href' => 'https://envoyer.io',
    ],
    'forge' => [
        'id' => 'forge',
        'name' => 'Forge',
        'image-alt' => 'Forge',
        'description' => 'Server management doesn\'t have to be a nightmare.',
        'href' => 'https://forge.laravel.com',
    ],
    'herd' => [
        'id' => 'herd',
        'name' => 'Herd',
        'image-alt' => 'Herd',
        'description' => 'The fastest Laravel local development experience - exclusively for macOS.',
        'href' => 'https://herd.laravel.com',
    ],
    'horizon' => [
        'id' => 'horizon',
        'name' => 'Horizon',
        'image-alt' => 'Laravel Horizon',
        'description' => 'Beautiful UI for monitoring your Redis driven Laravel queues.',
        'href' => '/docs/' . DEFAULT_VERSION . '/horizon',
    ],
    'inertia' => [
        'id' => 'inertia',
        'name' => 'Inertia',
        'image-alt' => 'Inertia',
        'description' => 'Simplicity of JavaScript frameworks without the hassle of APIs.',
        'href' => 'https://inertiajs.com',
    ],
    'jetstream' => [
        'id' => 'jetstream',
        'name' => 'Jetstream',
        'image-alt' => 'Laravel Jetstream',
        'description' => 'Robust starter kit including authentication and team management.',
        'href' => 'https://jetstream.laravel.com',
    ],
    'livewire' => [
        'id' => 'livewire',
        'name' => 'Livewire',
        'image-alt' => 'Laravel Livewire',
        'description' => 'Build real-time applications without JavaScript.',
        'href' => 'https://livewire.laravel.com',
    ],
    'nova' => [
        'id' => 'nova',
        'name' => 'Nova',
        'image-alt' => 'Laravel Nova',
        'description' => 'Thoughtfully designed administration panel for your Laravel applications.',
        'href' => 'https://nova.laravel.com',
    ],
    'octane' => [
        'id' => 'octane',
        'name' => 'Octane',
        'image-alt' => 'Laravel Octane',
        'description' => 'Supercharge your application\'s performance by keeping it in memory.',
        'href' => '/docs/' . DEFAULT_VERSION . '/octane',
    ],
    'pennant' => [
        'id' => 'pennant',
        'name' => 'Pennant',
        'image-alt' => 'Laravel Pennant',
        'description' => 'A simple, lightweight library for managing feature flags.',
        'href' => '/docs/' . DEFAULT_VERSION . '/pennant',
    ],
    'pint' => [
        'id' => 'pint',
        'name' => 'Pint',
        'image-alt' => 'Laravel Pint',
        'description' => 'Opinionated PHP code style fixer for minimalists.',
        'href' => '/docs/' . DEFAULT_VERSION . '/pint',
    ],
    'prompts' => [
        'id' => 'prompts',
        'name' => 'Prompts',
        'image-alt' => 'Laravel Prompts',
        'description' => 'Next generation prompts for CLI tools.',
        'href' => '/docs/' . DEFAULT_VERSION . '/prompts',
    ],
    'sail' => [
        'id' => 'sail',
        'name' => 'Sail',
        'image-alt' => 'Laravel Sail',
        'description' => 'Hand-crafted Laravel local development experience using Docker.',
        'href' => '/docs/' . DEFAULT_VERSION . '/sail',
    ],
    'sanctum' => [
        'id' => 'sanctum',
        'name' => 'Sanctum',
        'image-alt' => 'Laravel Sanctum',
        'description' => 'API and mobile application authentication without wanting to pull your hair out.',
        'href' => '/docs/' . DEFAULT_VERSION . '/sanctum',
    ],
    'scout' => [
        'id' => 'scout',
        'name' => 'Scout',
        'image-alt' => 'Laravel Scout',
        'description' => 'Lightning fast full-text search for your application\'s Eloquent models.',
        'href' => '/docs/' . DEFAULT_VERSION . '/scout',
    ],
    'socialite' => [
        'id' => 'socialite',
        'name' => 'Socialite',
        'image-alt' => 'Laravel Socialite',
        'description' => 'Social authentication via Facebook, Twitter, GitHub, LinkedIn, and more.',
        'href' => '/docs/' . DEFAULT_VERSION . '/socialite',
    ],
    'spark' => [
        'id' => 'spark',
        'name' => 'Spark',
        'image-alt' => 'Laravel Spark',
        'description' => 'Launch your next business with our fully-featured, drop-in billing portal.',
        'href' => 'https://spark.laravel.com',
    ],
    'telescope' => [
        'id' => 'telescope',
        'name' => 'Telescope',
        'image-alt' => 'Laravel Telescope',
        'description' => 'Debug your application using our debugging and insight UI.',
        'href' => '/docs/' . DEFAULT_VERSION . '/telescope',
    ],
    'vapor' => [
        'id' => 'vapor',
        'name' => 'Vapor',
        'image-alt' => 'Laravel Vapor',
        'description' => 'Laravel Vapor is a serverless deployment platform for Laravel, powered by AWS.',
        'href' => 'https://vapor.laravel.com',
    ]
]);

define("TOP_MARKETING_ITEMS", [
    'forge' => [
        'id' => 'forge',
        'name' => 'Forge',
        'image-alt' => 'Forge',
        'description' => 'Server management doesn\'t have to be a nightmare. Provision and deploy unlimited PHP applications on DigitalOcean, Linode, Vultr, Amazon, Hetzner and more.',
        'href' => 'https://forge.laravel.com',
    ],
    'vapor' => [
        'id' => 'vapor',
        'name' => 'Vapor',
        'image-alt' => 'Vapor',
        'description' => 'Laravel Vapor is a serverless deployment platform for Laravel, powered by AWS. Launch your Laravel infrastructure on Vapor and fall in love with the scalable simplicity of serverless.',
        'href' => 'https://vapor.laravel.com',
    ],
]);
